# Generated by Django 3.1.2 on 2020-10-21 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201020_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 13, 24, 40, 407444)),
        ),
    ]
