# Generated by Django 3.1.2 on 2020-10-22 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201021_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 8, 53, 49, 262531)),
        ),
    ]
