# Generated by Django 3.1.2 on 2020-11-14 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20201113_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 10, 51, 59, 852173)),
        ),
    ]
